//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vue.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vue.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\logo cra.png.
        /// </summary>
        internal static string img_classe_cra {
            get {
                return ResourceManager.GetString("img_classe_cra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\logo ecaflip.png.
        /// </summary>
        internal static string img_classe_ecaflip {
            get {
                return ResourceManager.GetString("img_classe_ecaflip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\logo eniripsa.png.
        /// </summary>
        internal static string img_classe_eniripsa {
            get {
                return ResourceManager.GetString("img_classe_eniripsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\logo enutrof.png.
        /// </summary>
        internal static string img_classe_enutrof {
            get {
                return ResourceManager.GetString("img_classe_enutrof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\logo feca.png.
        /// </summary>
        internal static string img_classe_feca {
            get {
                return ResourceManager.GetString("img_classe_feca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\logo iop.png.
        /// </summary>
        internal static string img_classe_iop {
            get {
                return ResourceManager.GetString("img_classe_iop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\logo osamodas.png.
        /// </summary>
        internal static string img_classe_osamodas {
            get {
                return ResourceManager.GetString("img_classe_osamodas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\logo pandawa.png.
        /// </summary>
        internal static string img_classe_pandawa {
            get {
                return ResourceManager.GetString("img_classe_pandawa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\logo sacrieur.png.
        /// </summary>
        internal static string img_classe_sacrieur {
            get {
                return ResourceManager.GetString("img_classe_sacrieur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\logo sadida.png.
        /// </summary>
        internal static string img_classe_sadida {
            get {
                return ResourceManager.GetString("img_classe_sadida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\logo sram.png.
        /// </summary>
        internal static string img_classe_sram {
            get {
                return ResourceManager.GetString("img_classe_sram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\logo xelor.png.
        /// </summary>
        internal static string img_classe_xelor {
            get {
                return ResourceManager.GetString("img_classe_xelor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Cra\img_cra_sort1.png.
        /// </summary>
        internal static string img_cra_sort1 {
            get {
                return ResourceManager.GetString("img_cra_sort1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Cra\img_cra_sort10.png.
        /// </summary>
        internal static string img_cra_sort10 {
            get {
                return ResourceManager.GetString("img_cra_sort10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Cra\img_cra_sort11.png.
        /// </summary>
        internal static string img_cra_sort11 {
            get {
                return ResourceManager.GetString("img_cra_sort11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Cra\img_cra_sort12.png.
        /// </summary>
        internal static string img_cra_sort12 {
            get {
                return ResourceManager.GetString("img_cra_sort12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Cra\img_cra_sort13.png.
        /// </summary>
        internal static string img_cra_sort13 {
            get {
                return ResourceManager.GetString("img_cra_sort13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Cra\img_cra_sort14.png.
        /// </summary>
        internal static string img_cra_sort14 {
            get {
                return ResourceManager.GetString("img_cra_sort14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Cra\img_cra_sort15.png.
        /// </summary>
        internal static string img_cra_sort15 {
            get {
                return ResourceManager.GetString("img_cra_sort15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Cra\img_cra_sort16.png.
        /// </summary>
        internal static string img_cra_sort16 {
            get {
                return ResourceManager.GetString("img_cra_sort16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Cra\img_cra_sort17.png.
        /// </summary>
        internal static string img_cra_sort17 {
            get {
                return ResourceManager.GetString("img_cra_sort17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Cra\img_cra_sort18.png.
        /// </summary>
        internal static string img_cra_sort18 {
            get {
                return ResourceManager.GetString("img_cra_sort18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Cra\img_cra_sort19.png.
        /// </summary>
        internal static string img_cra_sort19 {
            get {
                return ResourceManager.GetString("img_cra_sort19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Cra\img_cra_sort2.png.
        /// </summary>
        internal static string img_cra_sort2 {
            get {
                return ResourceManager.GetString("img_cra_sort2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Cra\img_cra_sort20.png.
        /// </summary>
        internal static string img_cra_sort20 {
            get {
                return ResourceManager.GetString("img_cra_sort20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Cra\img_cra_sort21.png.
        /// </summary>
        internal static string img_cra_sort21 {
            get {
                return ResourceManager.GetString("img_cra_sort21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Cra\img_cra_sort3.png.
        /// </summary>
        internal static string img_cra_sort3 {
            get {
                return ResourceManager.GetString("img_cra_sort3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Cra\img_cra_sort4.png.
        /// </summary>
        internal static string img_cra_sort4 {
            get {
                return ResourceManager.GetString("img_cra_sort4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Cra\img_cra_sort5.png.
        /// </summary>
        internal static string img_cra_sort5 {
            get {
                return ResourceManager.GetString("img_cra_sort5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Cra\img_cra_sort6.png.
        /// </summary>
        internal static string img_cra_sort6 {
            get {
                return ResourceManager.GetString("img_cra_sort6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Cra\img_cra_sort7.png.
        /// </summary>
        internal static string img_cra_sort7 {
            get {
                return ResourceManager.GetString("img_cra_sort7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Cra\img_cra_sort8.png.
        /// </summary>
        internal static string img_cra_sort8 {
            get {
                return ResourceManager.GetString("img_cra_sort8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Cra\img_cra_sort9.png.
        /// </summary>
        internal static string img_cra_sort9 {
            get {
                return ResourceManager.GetString("img_cra_sort9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Ecaflip\img_ecaflip_sort1.png.
        /// </summary>
        internal static string img_ecaflip_sort1 {
            get {
                return ResourceManager.GetString("img_ecaflip_sort1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Ecaflip\img_ecaflip_sort10.png.
        /// </summary>
        internal static string img_ecaflip_sort10 {
            get {
                return ResourceManager.GetString("img_ecaflip_sort10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Ecaflip\img_ecaflip_sort11.png.
        /// </summary>
        internal static string img_ecaflip_sort11 {
            get {
                return ResourceManager.GetString("img_ecaflip_sort11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Ecaflip\img_ecaflip_sort12.png.
        /// </summary>
        internal static string img_ecaflip_sort12 {
            get {
                return ResourceManager.GetString("img_ecaflip_sort12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Ecaflip\img_ecaflip_sort13.png.
        /// </summary>
        internal static string img_ecaflip_sort13 {
            get {
                return ResourceManager.GetString("img_ecaflip_sort13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Ecaflip\img_ecaflip_sort14.png.
        /// </summary>
        internal static string img_ecaflip_sort14 {
            get {
                return ResourceManager.GetString("img_ecaflip_sort14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Ecaflip\img_ecaflip_sort15.png.
        /// </summary>
        internal static string img_ecaflip_sort15 {
            get {
                return ResourceManager.GetString("img_ecaflip_sort15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Ecaflip\img_ecaflip_sort16.png.
        /// </summary>
        internal static string img_ecaflip_sort16 {
            get {
                return ResourceManager.GetString("img_ecaflip_sort16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Ecaflip\img_ecaflip_sort17.png.
        /// </summary>
        internal static string img_ecaflip_sort17 {
            get {
                return ResourceManager.GetString("img_ecaflip_sort17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Ecaflip\img_ecaflip_sort18.png.
        /// </summary>
        internal static string img_ecaflip_sort18 {
            get {
                return ResourceManager.GetString("img_ecaflip_sort18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Ecaflip\img_ecaflip_sort19.png.
        /// </summary>
        internal static string img_ecaflip_sort19 {
            get {
                return ResourceManager.GetString("img_ecaflip_sort19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Ecaflip\img_ecaflip_sort2.png.
        /// </summary>
        internal static string img_ecaflip_sort2 {
            get {
                return ResourceManager.GetString("img_ecaflip_sort2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Ecaflip\img_ecaflip_sort20.png.
        /// </summary>
        internal static string img_ecaflip_sort20 {
            get {
                return ResourceManager.GetString("img_ecaflip_sort20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Ecaflip\img_ecaflip_sort21.png.
        /// </summary>
        internal static string img_ecaflip_sort21 {
            get {
                return ResourceManager.GetString("img_ecaflip_sort21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Ecaflip\img_ecaflip_sort3.png.
        /// </summary>
        internal static string img_ecaflip_sort3 {
            get {
                return ResourceManager.GetString("img_ecaflip_sort3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Ecaflip\img_ecaflip_sort4.png.
        /// </summary>
        internal static string img_ecaflip_sort4 {
            get {
                return ResourceManager.GetString("img_ecaflip_sort4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Ecaflip\img_ecaflip_sort5.png.
        /// </summary>
        internal static string img_ecaflip_sort5 {
            get {
                return ResourceManager.GetString("img_ecaflip_sort5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Ecaflip\img_ecaflip_sort6.png.
        /// </summary>
        internal static string img_ecaflip_sort6 {
            get {
                return ResourceManager.GetString("img_ecaflip_sort6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Ecaflip\img_ecaflip_sort7.png.
        /// </summary>
        internal static string img_ecaflip_sort7 {
            get {
                return ResourceManager.GetString("img_ecaflip_sort7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Ecaflip\img_ecaflip_sort8.png.
        /// </summary>
        internal static string img_ecaflip_sort8 {
            get {
                return ResourceManager.GetString("img_ecaflip_sort8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Ecaflip\img_ecaflip_sort9.png.
        /// </summary>
        internal static string img_ecaflip_sort9 {
            get {
                return ResourceManager.GetString("img_ecaflip_sort9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Eniripsa\img_eniripsa_sort1.png.
        /// </summary>
        internal static string img_eniripsa_sort1 {
            get {
                return ResourceManager.GetString("img_eniripsa_sort1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Eniripsa\img_eniripsa_sort10.png.
        /// </summary>
        internal static string img_eniripsa_sort10 {
            get {
                return ResourceManager.GetString("img_eniripsa_sort10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Eniripsa\img_eniripsa_sort11.png.
        /// </summary>
        internal static string img_eniripsa_sort11 {
            get {
                return ResourceManager.GetString("img_eniripsa_sort11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Eniripsa\img_eniripsa_sort12.png.
        /// </summary>
        internal static string img_eniripsa_sort12 {
            get {
                return ResourceManager.GetString("img_eniripsa_sort12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Eniripsa\img_eniripsa_sort13.png.
        /// </summary>
        internal static string img_eniripsa_sort13 {
            get {
                return ResourceManager.GetString("img_eniripsa_sort13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Eniripsa\img_eniripsa_sort14.png.
        /// </summary>
        internal static string img_eniripsa_sort14 {
            get {
                return ResourceManager.GetString("img_eniripsa_sort14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Eniripsa\img_eniripsa_sort15.png.
        /// </summary>
        internal static string img_eniripsa_sort15 {
            get {
                return ResourceManager.GetString("img_eniripsa_sort15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Eniripsa\img_eniripsa_sort16.png.
        /// </summary>
        internal static string img_eniripsa_sort16 {
            get {
                return ResourceManager.GetString("img_eniripsa_sort16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Eniripsa\img_eniripsa_sort17.png.
        /// </summary>
        internal static string img_eniripsa_sort17 {
            get {
                return ResourceManager.GetString("img_eniripsa_sort17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Eniripsa\img_eniripsa_sort18.png.
        /// </summary>
        internal static string img_eniripsa_sort18 {
            get {
                return ResourceManager.GetString("img_eniripsa_sort18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Eniripsa\img_eniripsa_sort19.png.
        /// </summary>
        internal static string img_eniripsa_sort19 {
            get {
                return ResourceManager.GetString("img_eniripsa_sort19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Eniripsa\img_eniripsa_sort2.png.
        /// </summary>
        internal static string img_eniripsa_sort2 {
            get {
                return ResourceManager.GetString("img_eniripsa_sort2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Eniripsa\img_eniripsa_sort20.png.
        /// </summary>
        internal static string img_eniripsa_sort20 {
            get {
                return ResourceManager.GetString("img_eniripsa_sort20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Eniripsa\img_eniripsa_sort21.png.
        /// </summary>
        internal static string img_eniripsa_sort21 {
            get {
                return ResourceManager.GetString("img_eniripsa_sort21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Eniripsa\img_eniripsa_sort3.png.
        /// </summary>
        internal static string img_eniripsa_sort3 {
            get {
                return ResourceManager.GetString("img_eniripsa_sort3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Eniripsa\img_eniripsa_sort4.png.
        /// </summary>
        internal static string img_eniripsa_sort4 {
            get {
                return ResourceManager.GetString("img_eniripsa_sort4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Eniripsa\img_eniripsa_sort5.png.
        /// </summary>
        internal static string img_eniripsa_sort5 {
            get {
                return ResourceManager.GetString("img_eniripsa_sort5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Eniripsa\img_eniripsa_sort6.png.
        /// </summary>
        internal static string img_eniripsa_sort6 {
            get {
                return ResourceManager.GetString("img_eniripsa_sort6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Eniripsa\img_eniripsa_sort7.png.
        /// </summary>
        internal static string img_eniripsa_sort7 {
            get {
                return ResourceManager.GetString("img_eniripsa_sort7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Eniripsa\img_eniripsa_sort8.png.
        /// </summary>
        internal static string img_eniripsa_sort8 {
            get {
                return ResourceManager.GetString("img_eniripsa_sort8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Eniripsa\img_eniripsa_sort9.png.
        /// </summary>
        internal static string img_eniripsa_sort9 {
            get {
                return ResourceManager.GetString("img_eniripsa_sort9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Enutrof\img_enutrof_sort1.png.
        /// </summary>
        internal static string img_enutrof_sort1 {
            get {
                return ResourceManager.GetString("img_enutrof_sort1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Enutrof\img_enutrof_sort10.png.
        /// </summary>
        internal static string img_enutrof_sort10 {
            get {
                return ResourceManager.GetString("img_enutrof_sort10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Enutrof\img_enutrof_sort11.png.
        /// </summary>
        internal static string img_enutrof_sort11 {
            get {
                return ResourceManager.GetString("img_enutrof_sort11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Enutrof\img_enutrof_sort12.png.
        /// </summary>
        internal static string img_enutrof_sort12 {
            get {
                return ResourceManager.GetString("img_enutrof_sort12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Enutrof\img_enutrof_sort13.png.
        /// </summary>
        internal static string img_enutrof_sort13 {
            get {
                return ResourceManager.GetString("img_enutrof_sort13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Enutrof\img_enutrof_sort14.png.
        /// </summary>
        internal static string img_enutrof_sort14 {
            get {
                return ResourceManager.GetString("img_enutrof_sort14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Enutrof\img_enutrof_sort15.png.
        /// </summary>
        internal static string img_enutrof_sort15 {
            get {
                return ResourceManager.GetString("img_enutrof_sort15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Enutrof\img_enutrof_sort16.png.
        /// </summary>
        internal static string img_enutrof_sort16 {
            get {
                return ResourceManager.GetString("img_enutrof_sort16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Enutrof\img_enutrof_sort17.png.
        /// </summary>
        internal static string img_enutrof_sort17 {
            get {
                return ResourceManager.GetString("img_enutrof_sort17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Enutrof\img_enutrof_sort18.png.
        /// </summary>
        internal static string img_enutrof_sort18 {
            get {
                return ResourceManager.GetString("img_enutrof_sort18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Enutrof\img_enutrof_sort19.png.
        /// </summary>
        internal static string img_enutrof_sort19 {
            get {
                return ResourceManager.GetString("img_enutrof_sort19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Enutrof\img_enutrof_sort2.png.
        /// </summary>
        internal static string img_enutrof_sort2 {
            get {
                return ResourceManager.GetString("img_enutrof_sort2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Enutrof\img_enutrof_sort20.png.
        /// </summary>
        internal static string img_enutrof_sort20 {
            get {
                return ResourceManager.GetString("img_enutrof_sort20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Enutrof\img_enutrof_sort21.png.
        /// </summary>
        internal static string img_enutrof_sort21 {
            get {
                return ResourceManager.GetString("img_enutrof_sort21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Enutrof\img_enutrof_sort3.png.
        /// </summary>
        internal static string img_enutrof_sort3 {
            get {
                return ResourceManager.GetString("img_enutrof_sort3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Enutrof\img_enutrof_sort4.png.
        /// </summary>
        internal static string img_enutrof_sort4 {
            get {
                return ResourceManager.GetString("img_enutrof_sort4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Enutrof\img_enutrof_sort5.png.
        /// </summary>
        internal static string img_enutrof_sort5 {
            get {
                return ResourceManager.GetString("img_enutrof_sort5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Enutrof\img_enutrof_sort6.png.
        /// </summary>
        internal static string img_enutrof_sort6 {
            get {
                return ResourceManager.GetString("img_enutrof_sort6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Enutrof\img_enutrof_sort7.png.
        /// </summary>
        internal static string img_enutrof_sort7 {
            get {
                return ResourceManager.GetString("img_enutrof_sort7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Enutrof\img_enutrof_sort8.png.
        /// </summary>
        internal static string img_enutrof_sort8 {
            get {
                return ResourceManager.GetString("img_enutrof_sort8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Enutrof\img_enutrof_sort9.png.
        /// </summary>
        internal static string img_enutrof_sort9 {
            get {
                return ResourceManager.GetString("img_enutrof_sort9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Feca\img_feca_sort1.png.
        /// </summary>
        internal static string img_feca_sort1 {
            get {
                return ResourceManager.GetString("img_feca_sort1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Feca\img_feca_sort10.png.
        /// </summary>
        internal static string img_feca_sort10 {
            get {
                return ResourceManager.GetString("img_feca_sort10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Feca\img_feca_sort11.png.
        /// </summary>
        internal static string img_feca_sort11 {
            get {
                return ResourceManager.GetString("img_feca_sort11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Feca\img_feca_sort12.png.
        /// </summary>
        internal static string img_feca_sort12 {
            get {
                return ResourceManager.GetString("img_feca_sort12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Feca\img_feca_sort13.png.
        /// </summary>
        internal static string img_feca_sort13 {
            get {
                return ResourceManager.GetString("img_feca_sort13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Feca\img_feca_sort14.png.
        /// </summary>
        internal static string img_feca_sort14 {
            get {
                return ResourceManager.GetString("img_feca_sort14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Feca\img_feca_sort15.png.
        /// </summary>
        internal static string img_feca_sort15 {
            get {
                return ResourceManager.GetString("img_feca_sort15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Feca\img_feca_sort16.png.
        /// </summary>
        internal static string img_feca_sort16 {
            get {
                return ResourceManager.GetString("img_feca_sort16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Feca\img_feca_sort17.png.
        /// </summary>
        internal static string img_feca_sort17 {
            get {
                return ResourceManager.GetString("img_feca_sort17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Feca\img_feca_sort18.png.
        /// </summary>
        internal static string img_feca_sort18 {
            get {
                return ResourceManager.GetString("img_feca_sort18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Feca\img_feca_sort19.png.
        /// </summary>
        internal static string img_feca_sort19 {
            get {
                return ResourceManager.GetString("img_feca_sort19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Feca\img_feca_sort2.png.
        /// </summary>
        internal static string img_feca_sort2 {
            get {
                return ResourceManager.GetString("img_feca_sort2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Feca\img_feca_sort20.png.
        /// </summary>
        internal static string img_feca_sort20 {
            get {
                return ResourceManager.GetString("img_feca_sort20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Feca\img_feca_sort21.png.
        /// </summary>
        internal static string img_feca_sort21 {
            get {
                return ResourceManager.GetString("img_feca_sort21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Feca\img_feca_sort3.png.
        /// </summary>
        internal static string img_feca_sort3 {
            get {
                return ResourceManager.GetString("img_feca_sort3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Feca\img_feca_sort4.png.
        /// </summary>
        internal static string img_feca_sort4 {
            get {
                return ResourceManager.GetString("img_feca_sort4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Feca\img_feca_sort5.png.
        /// </summary>
        internal static string img_feca_sort5 {
            get {
                return ResourceManager.GetString("img_feca_sort5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Feca\img_feca_sort6.png.
        /// </summary>
        internal static string img_feca_sort6 {
            get {
                return ResourceManager.GetString("img_feca_sort6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Feca\img_feca_sort7.png.
        /// </summary>
        internal static string img_feca_sort7 {
            get {
                return ResourceManager.GetString("img_feca_sort7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Feca\img_feca_sort8.png.
        /// </summary>
        internal static string img_feca_sort8 {
            get {
                return ResourceManager.GetString("img_feca_sort8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Feca\img_feca_sort9.png.
        /// </summary>
        internal static string img_feca_sort9 {
            get {
                return ResourceManager.GetString("img_feca_sort9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Iop\img_iop_sort1.png.
        /// </summary>
        internal static string img_iop_sort1 {
            get {
                return ResourceManager.GetString("img_iop_sort1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Iop\img_iop_sort10.png.
        /// </summary>
        internal static string img_iop_sort10 {
            get {
                return ResourceManager.GetString("img_iop_sort10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Iop\img_iop_sort11.png.
        /// </summary>
        internal static string img_iop_sort11 {
            get {
                return ResourceManager.GetString("img_iop_sort11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Iop\img_iop_sort12.png.
        /// </summary>
        internal static string img_iop_sort12 {
            get {
                return ResourceManager.GetString("img_iop_sort12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Iop\img_iop_sort13.png.
        /// </summary>
        internal static string img_iop_sort13 {
            get {
                return ResourceManager.GetString("img_iop_sort13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Iop\img_iop_sort14.png.
        /// </summary>
        internal static string img_iop_sort14 {
            get {
                return ResourceManager.GetString("img_iop_sort14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Iop\img_iop_sort15.png.
        /// </summary>
        internal static string img_iop_sort15 {
            get {
                return ResourceManager.GetString("img_iop_sort15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Iop\img_iop_sort16.png.
        /// </summary>
        internal static string img_iop_sort16 {
            get {
                return ResourceManager.GetString("img_iop_sort16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Iop\img_iop_sort17.png.
        /// </summary>
        internal static string img_iop_sort17 {
            get {
                return ResourceManager.GetString("img_iop_sort17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Iop\img_iop_sort18.png.
        /// </summary>
        internal static string img_iop_sort18 {
            get {
                return ResourceManager.GetString("img_iop_sort18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Iop\img_iop_sort19.png.
        /// </summary>
        internal static string img_iop_sort19 {
            get {
                return ResourceManager.GetString("img_iop_sort19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Iop\img_iop_sort2.png.
        /// </summary>
        internal static string img_iop_sort2 {
            get {
                return ResourceManager.GetString("img_iop_sort2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Iop\img_iop_sort20.png.
        /// </summary>
        internal static string img_iop_sort20 {
            get {
                return ResourceManager.GetString("img_iop_sort20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Iop\img_iop_sort21.png.
        /// </summary>
        internal static string img_iop_sort21 {
            get {
                return ResourceManager.GetString("img_iop_sort21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Iop\img_iop_sort3.png.
        /// </summary>
        internal static string img_iop_sort3 {
            get {
                return ResourceManager.GetString("img_iop_sort3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Iop\img_iop_sort4.png.
        /// </summary>
        internal static string img_iop_sort4 {
            get {
                return ResourceManager.GetString("img_iop_sort4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Iop\img_iop_sort5.png.
        /// </summary>
        internal static string img_iop_sort5 {
            get {
                return ResourceManager.GetString("img_iop_sort5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Iop\img_iop_sort6.png.
        /// </summary>
        internal static string img_iop_sort6 {
            get {
                return ResourceManager.GetString("img_iop_sort6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Iop\img_iop_sort7.png.
        /// </summary>
        internal static string img_iop_sort7 {
            get {
                return ResourceManager.GetString("img_iop_sort7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Iop\img_iop_sort8.png.
        /// </summary>
        internal static string img_iop_sort8 {
            get {
                return ResourceManager.GetString("img_iop_sort8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Iop\img_iop_sort9.png.
        /// </summary>
        internal static string img_iop_sort9 {
            get {
                return ResourceManager.GetString("img_iop_sort9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Logo.png.
        /// </summary>
        internal static string img_logo {
            get {
                return ResourceManager.GetString("img_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Osamodas\img_osamodas_sort1.png.
        /// </summary>
        internal static string img_osamodas_sort1 {
            get {
                return ResourceManager.GetString("img_osamodas_sort1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Osamodas\img_osamodas_sort10.png.
        /// </summary>
        internal static string img_osamodas_sort10 {
            get {
                return ResourceManager.GetString("img_osamodas_sort10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Osamodas\img_osamodas_sort11.png.
        /// </summary>
        internal static string img_osamodas_sort11 {
            get {
                return ResourceManager.GetString("img_osamodas_sort11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Osamodas\img_osamodas_sort12.png.
        /// </summary>
        internal static string img_osamodas_sort12 {
            get {
                return ResourceManager.GetString("img_osamodas_sort12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Osamodas\img_osamodas_sort13.png.
        /// </summary>
        internal static string img_osamodas_sort13 {
            get {
                return ResourceManager.GetString("img_osamodas_sort13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Osamodas\img_osamodas_sort14.png.
        /// </summary>
        internal static string img_osamodas_sort14 {
            get {
                return ResourceManager.GetString("img_osamodas_sort14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Osamodas\img_osamodas_sort15.png.
        /// </summary>
        internal static string img_osamodas_sort15 {
            get {
                return ResourceManager.GetString("img_osamodas_sort15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Osamodas\img_osamodas_sort16.png.
        /// </summary>
        internal static string img_osamodas_sort16 {
            get {
                return ResourceManager.GetString("img_osamodas_sort16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Osamodas\img_osamodas_sort17.png.
        /// </summary>
        internal static string img_osamodas_sort17 {
            get {
                return ResourceManager.GetString("img_osamodas_sort17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Osamodas\img_osamodas_sort18.png.
        /// </summary>
        internal static string img_osamodas_sort18 {
            get {
                return ResourceManager.GetString("img_osamodas_sort18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Osamodas\img_osamodas_sort19.png.
        /// </summary>
        internal static string img_osamodas_sort19 {
            get {
                return ResourceManager.GetString("img_osamodas_sort19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Osamodas\img_osamodas_sort2.png.
        /// </summary>
        internal static string img_osamodas_sort2 {
            get {
                return ResourceManager.GetString("img_osamodas_sort2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Osamodas\img_osamodas_sort20.png.
        /// </summary>
        internal static string img_osamodas_sort20 {
            get {
                return ResourceManager.GetString("img_osamodas_sort20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Osamodas\img_osamodas_sort21.png.
        /// </summary>
        internal static string img_osamodas_sort21 {
            get {
                return ResourceManager.GetString("img_osamodas_sort21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Osamodas\img_osamodas_sort3.png.
        /// </summary>
        internal static string img_osamodas_sort3 {
            get {
                return ResourceManager.GetString("img_osamodas_sort3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Osamodas\img_osamodas_sort4.png.
        /// </summary>
        internal static string img_osamodas_sort4 {
            get {
                return ResourceManager.GetString("img_osamodas_sort4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Osamodas\img_osamodas_sort5.png.
        /// </summary>
        internal static string img_osamodas_sort5 {
            get {
                return ResourceManager.GetString("img_osamodas_sort5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Osamodas\img_osamodas_sort6.png.
        /// </summary>
        internal static string img_osamodas_sort6 {
            get {
                return ResourceManager.GetString("img_osamodas_sort6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Osamodas\img_osamodas_sort7.png.
        /// </summary>
        internal static string img_osamodas_sort7 {
            get {
                return ResourceManager.GetString("img_osamodas_sort7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Osamodas\img_osamodas_sort8.png.
        /// </summary>
        internal static string img_osamodas_sort8 {
            get {
                return ResourceManager.GetString("img_osamodas_sort8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Osamodas\img_osamodas_sort9.png.
        /// </summary>
        internal static string img_osamodas_sort9 {
            get {
                return ResourceManager.GetString("img_osamodas_sort9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Pandawa\img_pandawa_sort1.png.
        /// </summary>
        internal static string img_pandawa_sort1 {
            get {
                return ResourceManager.GetString("img_pandawa_sort1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Pandawa\img_pandawa_sort10.png.
        /// </summary>
        internal static string img_pandawa_sort10 {
            get {
                return ResourceManager.GetString("img_pandawa_sort10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Pandawa\img_pandawa_sort11.png.
        /// </summary>
        internal static string img_pandawa_sort11 {
            get {
                return ResourceManager.GetString("img_pandawa_sort11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Pandawa\img_pandawa_sort12.png.
        /// </summary>
        internal static string img_pandawa_sort12 {
            get {
                return ResourceManager.GetString("img_pandawa_sort12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Pandawa\img_pandawa_sort13.png.
        /// </summary>
        internal static string img_pandawa_sort13 {
            get {
                return ResourceManager.GetString("img_pandawa_sort13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Pandawa\img_pandawa_sort14.png.
        /// </summary>
        internal static string img_pandawa_sort14 {
            get {
                return ResourceManager.GetString("img_pandawa_sort14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Pandawa\img_pandawa_sort15.png.
        /// </summary>
        internal static string img_pandawa_sort15 {
            get {
                return ResourceManager.GetString("img_pandawa_sort15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Pandawa\img_pandawa_sort16.png.
        /// </summary>
        internal static string img_pandawa_sort16 {
            get {
                return ResourceManager.GetString("img_pandawa_sort16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Pandawa\img_pandawa_sort17.png.
        /// </summary>
        internal static string img_pandawa_sort17 {
            get {
                return ResourceManager.GetString("img_pandawa_sort17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Pandawa\img_pandawa_sort18.png.
        /// </summary>
        internal static string img_pandawa_sort18 {
            get {
                return ResourceManager.GetString("img_pandawa_sort18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Pandawa\img_pandawa_sort19.png.
        /// </summary>
        internal static string img_pandawa_sort19 {
            get {
                return ResourceManager.GetString("img_pandawa_sort19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Pandawa\img_pandawa_sort2.png.
        /// </summary>
        internal static string img_pandawa_sort2 {
            get {
                return ResourceManager.GetString("img_pandawa_sort2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Pandawa\img_pandawa_sort20.png.
        /// </summary>
        internal static string img_pandawa_sort20 {
            get {
                return ResourceManager.GetString("img_pandawa_sort20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Pandawa\img_pandawa_sort21.png.
        /// </summary>
        internal static string img_pandawa_sort21 {
            get {
                return ResourceManager.GetString("img_pandawa_sort21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Pandawa\img_pandawa_sort3.png.
        /// </summary>
        internal static string img_pandawa_sort3 {
            get {
                return ResourceManager.GetString("img_pandawa_sort3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Pandawa\img_pandawa_sort4.png.
        /// </summary>
        internal static string img_pandawa_sort4 {
            get {
                return ResourceManager.GetString("img_pandawa_sort4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Pandawa\img_pandawa_sort5.png.
        /// </summary>
        internal static string img_pandawa_sort5 {
            get {
                return ResourceManager.GetString("img_pandawa_sort5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Pandawa\img_pandawa_sort6.png.
        /// </summary>
        internal static string img_pandawa_sort6 {
            get {
                return ResourceManager.GetString("img_pandawa_sort6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Pandawa\img_pandawa_sort7.png.
        /// </summary>
        internal static string img_pandawa_sort7 {
            get {
                return ResourceManager.GetString("img_pandawa_sort7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Pandawa\img_pandawa_sort8.png.
        /// </summary>
        internal static string img_pandawa_sort8 {
            get {
                return ResourceManager.GetString("img_pandawa_sort8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Pandawa\img_pandawa_sort9.png.
        /// </summary>
        internal static string img_pandawa_sort9 {
            get {
                return ResourceManager.GetString("img_pandawa_sort9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sacrieur\img_sacrieur_sort1.png.
        /// </summary>
        internal static string img_sacrieur_sort1 {
            get {
                return ResourceManager.GetString("img_sacrieur_sort1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sacrieur\img_sacrieur_sort10.png.
        /// </summary>
        internal static string img_sacrieur_sort10 {
            get {
                return ResourceManager.GetString("img_sacrieur_sort10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sacrieur\img_sacrieur_sort11.png.
        /// </summary>
        internal static string img_sacrieur_sort11 {
            get {
                return ResourceManager.GetString("img_sacrieur_sort11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sacrieur\img_sacrieur_sort12.png.
        /// </summary>
        internal static string img_sacrieur_sort12 {
            get {
                return ResourceManager.GetString("img_sacrieur_sort12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sacrieur\img_sacrieur_sort13.png.
        /// </summary>
        internal static string img_sacrieur_sort13 {
            get {
                return ResourceManager.GetString("img_sacrieur_sort13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sacrieur\img_sacrieur_sort14.png.
        /// </summary>
        internal static string img_sacrieur_sort14 {
            get {
                return ResourceManager.GetString("img_sacrieur_sort14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sacrieur\img_sacrieur_sort15.png.
        /// </summary>
        internal static string img_sacrieur_sort15 {
            get {
                return ResourceManager.GetString("img_sacrieur_sort15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sacrieur\img_sacrieur_sort16.png.
        /// </summary>
        internal static string img_sacrieur_sort16 {
            get {
                return ResourceManager.GetString("img_sacrieur_sort16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sacrieur\img_sacrieur_sort17.png.
        /// </summary>
        internal static string img_sacrieur_sort17 {
            get {
                return ResourceManager.GetString("img_sacrieur_sort17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sacrieur\img_sacrieur_sort18.png.
        /// </summary>
        internal static string img_sacrieur_sort18 {
            get {
                return ResourceManager.GetString("img_sacrieur_sort18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sacrieur\img_sacrieur_sort19.png.
        /// </summary>
        internal static string img_sacrieur_sort19 {
            get {
                return ResourceManager.GetString("img_sacrieur_sort19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sacrieur\img_sacrieur_sort2.png.
        /// </summary>
        internal static string img_sacrieur_sort2 {
            get {
                return ResourceManager.GetString("img_sacrieur_sort2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sacrieur\img_sacrieur_sort20.png.
        /// </summary>
        internal static string img_sacrieur_sort20 {
            get {
                return ResourceManager.GetString("img_sacrieur_sort20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sacrieur\img_sacrieur_sort21.png.
        /// </summary>
        internal static string img_sacrieur_sort21 {
            get {
                return ResourceManager.GetString("img_sacrieur_sort21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sacrieur\img_sacrieur_sort3.png.
        /// </summary>
        internal static string img_sacrieur_sort3 {
            get {
                return ResourceManager.GetString("img_sacrieur_sort3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sacrieur\img_sacrieur_sort4.png.
        /// </summary>
        internal static string img_sacrieur_sort4 {
            get {
                return ResourceManager.GetString("img_sacrieur_sort4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sacrieur\img_sacrieur_sort5.png.
        /// </summary>
        internal static string img_sacrieur_sort5 {
            get {
                return ResourceManager.GetString("img_sacrieur_sort5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sacrieur\img_sacrieur_sort6.png.
        /// </summary>
        internal static string img_sacrieur_sort6 {
            get {
                return ResourceManager.GetString("img_sacrieur_sort6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sacrieur\img_sacrieur_sort7.png.
        /// </summary>
        internal static string img_sacrieur_sort7 {
            get {
                return ResourceManager.GetString("img_sacrieur_sort7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sacrieur\img_sacrieur_sort8.png.
        /// </summary>
        internal static string img_sacrieur_sort8 {
            get {
                return ResourceManager.GetString("img_sacrieur_sort8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sacrieur\img_sacrieur_sort9.png.
        /// </summary>
        internal static string img_sacrieur_sort9 {
            get {
                return ResourceManager.GetString("img_sacrieur_sort9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sadida\img_sadida_sort1.png.
        /// </summary>
        internal static string img_sadida_sort1 {
            get {
                return ResourceManager.GetString("img_sadida_sort1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sadida\img_sadida_sort10.png.
        /// </summary>
        internal static string img_sadida_sort10 {
            get {
                return ResourceManager.GetString("img_sadida_sort10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sadida\img_sadida_sort11.png.
        /// </summary>
        internal static string img_sadida_sort11 {
            get {
                return ResourceManager.GetString("img_sadida_sort11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sadida\img_sadida_sort12.png.
        /// </summary>
        internal static string img_sadida_sort12 {
            get {
                return ResourceManager.GetString("img_sadida_sort12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sadida\img_sadida_sort13.png.
        /// </summary>
        internal static string img_sadida_sort13 {
            get {
                return ResourceManager.GetString("img_sadida_sort13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sadida\img_sadida_sort14.png.
        /// </summary>
        internal static string img_sadida_sort14 {
            get {
                return ResourceManager.GetString("img_sadida_sort14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sadida\img_sadida_sort15.png.
        /// </summary>
        internal static string img_sadida_sort15 {
            get {
                return ResourceManager.GetString("img_sadida_sort15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sadida\img_sadida_sort16.png.
        /// </summary>
        internal static string img_sadida_sort16 {
            get {
                return ResourceManager.GetString("img_sadida_sort16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sadida\img_sadida_sort17.png.
        /// </summary>
        internal static string img_sadida_sort17 {
            get {
                return ResourceManager.GetString("img_sadida_sort17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sadida\img_sadida_sort18.png.
        /// </summary>
        internal static string img_sadida_sort18 {
            get {
                return ResourceManager.GetString("img_sadida_sort18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sadida\img_sadida_sort19.png.
        /// </summary>
        internal static string img_sadida_sort19 {
            get {
                return ResourceManager.GetString("img_sadida_sort19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sadida\img_sadida_sort2.png.
        /// </summary>
        internal static string img_sadida_sort2 {
            get {
                return ResourceManager.GetString("img_sadida_sort2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sadida\img_sadida_sort20.png.
        /// </summary>
        internal static string img_sadida_sort20 {
            get {
                return ResourceManager.GetString("img_sadida_sort20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sadida\img_sadida_sort21.png.
        /// </summary>
        internal static string img_sadida_sort21 {
            get {
                return ResourceManager.GetString("img_sadida_sort21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sadida\img_sadida_sort3.png.
        /// </summary>
        internal static string img_sadida_sort3 {
            get {
                return ResourceManager.GetString("img_sadida_sort3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sadida\img_sadida_sort4.png.
        /// </summary>
        internal static string img_sadida_sort4 {
            get {
                return ResourceManager.GetString("img_sadida_sort4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sadida\img_sadida_sort5.png.
        /// </summary>
        internal static string img_sadida_sort5 {
            get {
                return ResourceManager.GetString("img_sadida_sort5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sadida\img_sadida_sort6.png.
        /// </summary>
        internal static string img_sadida_sort6 {
            get {
                return ResourceManager.GetString("img_sadida_sort6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sadida\img_sadida_sort7.png.
        /// </summary>
        internal static string img_sadida_sort7 {
            get {
                return ResourceManager.GetString("img_sadida_sort7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sadida\img_sadida_sort8.png.
        /// </summary>
        internal static string img_sadida_sort8 {
            get {
                return ResourceManager.GetString("img_sadida_sort8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sadida\img_sadida_sort9.png.
        /// </summary>
        internal static string img_sadida_sort9 {
            get {
                return ResourceManager.GetString("img_sadida_sort9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sram\img_sram_sort1.png.
        /// </summary>
        internal static string img_sram_sort1 {
            get {
                return ResourceManager.GetString("img_sram_sort1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sram\img_sram_sort10.png.
        /// </summary>
        internal static string img_sram_sort10 {
            get {
                return ResourceManager.GetString("img_sram_sort10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sram\img_sram_sort11.png.
        /// </summary>
        internal static string img_sram_sort11 {
            get {
                return ResourceManager.GetString("img_sram_sort11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sram\img_sram_sort12.png.
        /// </summary>
        internal static string img_sram_sort12 {
            get {
                return ResourceManager.GetString("img_sram_sort12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sram\img_sram_sort13.png.
        /// </summary>
        internal static string img_sram_sort13 {
            get {
                return ResourceManager.GetString("img_sram_sort13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sram\img_sram_sort14.png.
        /// </summary>
        internal static string img_sram_sort14 {
            get {
                return ResourceManager.GetString("img_sram_sort14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sram\img_sram_sort15.png.
        /// </summary>
        internal static string img_sram_sort15 {
            get {
                return ResourceManager.GetString("img_sram_sort15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sram\img_sram_sort16.png.
        /// </summary>
        internal static string img_sram_sort16 {
            get {
                return ResourceManager.GetString("img_sram_sort16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sram\img_sram_sort17.png.
        /// </summary>
        internal static string img_sram_sort17 {
            get {
                return ResourceManager.GetString("img_sram_sort17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sram\img_sram_sort18.png.
        /// </summary>
        internal static string img_sram_sort18 {
            get {
                return ResourceManager.GetString("img_sram_sort18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sram\img_sram_sort19.png.
        /// </summary>
        internal static string img_sram_sort19 {
            get {
                return ResourceManager.GetString("img_sram_sort19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sram\img_sram_sort2.png.
        /// </summary>
        internal static string img_sram_sort2 {
            get {
                return ResourceManager.GetString("img_sram_sort2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sram\img_sram_sort20.png.
        /// </summary>
        internal static string img_sram_sort20 {
            get {
                return ResourceManager.GetString("img_sram_sort20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sram\img_sram_sort21.png.
        /// </summary>
        internal static string img_sram_sort21 {
            get {
                return ResourceManager.GetString("img_sram_sort21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sram\img_sram_sort3.png.
        /// </summary>
        internal static string img_sram_sort3 {
            get {
                return ResourceManager.GetString("img_sram_sort3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sram\img_sram_sort4.png.
        /// </summary>
        internal static string img_sram_sort4 {
            get {
                return ResourceManager.GetString("img_sram_sort4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sram\img_sram_sort5.png.
        /// </summary>
        internal static string img_sram_sort5 {
            get {
                return ResourceManager.GetString("img_sram_sort5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sram\img_sram_sort6.png.
        /// </summary>
        internal static string img_sram_sort6 {
            get {
                return ResourceManager.GetString("img_sram_sort6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sram\img_sram_sort7.png.
        /// </summary>
        internal static string img_sram_sort7 {
            get {
                return ResourceManager.GetString("img_sram_sort7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sram\img_sram_sort8.png.
        /// </summary>
        internal static string img_sram_sort8 {
            get {
                return ResourceManager.GetString("img_sram_sort8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Sram\img_sram_sort9.png.
        /// </summary>
        internal static string img_sram_sort9 {
            get {
                return ResourceManager.GetString("img_sram_sort9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Xelor\img_xelor_sort1.png.
        /// </summary>
        internal static string img_xelor_sort1 {
            get {
                return ResourceManager.GetString("img_xelor_sort1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Xelor\img_xelor_sort10.png.
        /// </summary>
        internal static string img_xelor_sort10 {
            get {
                return ResourceManager.GetString("img_xelor_sort10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Xelor\img_xelor_sort11.png.
        /// </summary>
        internal static string img_xelor_sort11 {
            get {
                return ResourceManager.GetString("img_xelor_sort11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Xelor\img_xelor_sort12.png.
        /// </summary>
        internal static string img_xelor_sort12 {
            get {
                return ResourceManager.GetString("img_xelor_sort12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Xelor\img_xelor_sort13.png.
        /// </summary>
        internal static string img_xelor_sort13 {
            get {
                return ResourceManager.GetString("img_xelor_sort13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Xelor\img_xelor_sort14.png.
        /// </summary>
        internal static string img_xelor_sort14 {
            get {
                return ResourceManager.GetString("img_xelor_sort14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Xelor\img_xelor_sort15.png.
        /// </summary>
        internal static string img_xelor_sort15 {
            get {
                return ResourceManager.GetString("img_xelor_sort15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Xelor\img_xelor_sort16.png.
        /// </summary>
        internal static string img_xelor_sort16 {
            get {
                return ResourceManager.GetString("img_xelor_sort16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Xelor\img_xelor_sort17.png.
        /// </summary>
        internal static string img_xelor_sort17 {
            get {
                return ResourceManager.GetString("img_xelor_sort17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Xelor\img_xelor_sort18.png.
        /// </summary>
        internal static string img_xelor_sort18 {
            get {
                return ResourceManager.GetString("img_xelor_sort18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Xelor\img_xelor_sort19.png.
        /// </summary>
        internal static string img_xelor_sort19 {
            get {
                return ResourceManager.GetString("img_xelor_sort19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Xelor\img_xelor_sort2.png.
        /// </summary>
        internal static string img_xelor_sort2 {
            get {
                return ResourceManager.GetString("img_xelor_sort2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Xelor\img_xelor_sort20.png.
        /// </summary>
        internal static string img_xelor_sort20 {
            get {
                return ResourceManager.GetString("img_xelor_sort20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Xelor\img_xelor_sort21.png.
        /// </summary>
        internal static string img_xelor_sort21 {
            get {
                return ResourceManager.GetString("img_xelor_sort21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Xelor\img_xelor_sort3.png.
        /// </summary>
        internal static string img_xelor_sort3 {
            get {
                return ResourceManager.GetString("img_xelor_sort3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Xelor\img_xelor_sort4.png.
        /// </summary>
        internal static string img_xelor_sort4 {
            get {
                return ResourceManager.GetString("img_xelor_sort4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Xelor\img_xelor_sort5.png.
        /// </summary>
        internal static string img_xelor_sort5 {
            get {
                return ResourceManager.GetString("img_xelor_sort5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Xelor\img_xelor_sort6.png.
        /// </summary>
        internal static string img_xelor_sort6 {
            get {
                return ResourceManager.GetString("img_xelor_sort6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Xelor\img_xelor_sort7.png.
        /// </summary>
        internal static string img_xelor_sort7 {
            get {
                return ResourceManager.GetString("img_xelor_sort7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Xelor\img_xelor_sort8.png.
        /// </summary>
        internal static string img_xelor_sort8 {
            get {
                return ResourceManager.GetString("img_xelor_sort8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .\Ressources\Sorts\Xelor\img_xelor_sort9.png.
        /// </summary>
        internal static string img_xelor_sort9 {
            get {
                return ResourceManager.GetString("img_xelor_sort9", resourceCulture);
            }
        }
    }
}
