using System.Collections.Generic;
using Vue.Properties;

namespace Vue
{
    public class Jeu
    {
        public List<ClasseView> ListClasses { get; private set; }

        public Jeu()
        {
            ListClasses = new List<ClasseView>()
            {
                new ClasseView(
                    "Cra",
                    "Les Cras sont des archers aussi fiers que précis ! \nIls font des alliés précieux contre les adeptes de la mêlée franche. \nRestant à distance, décochant leurs traits empennés dans le moindre orifice laissé sans surveillance, ils ne laissent aucun répit à leurs adversaires !",  
                    Resources.img_classe_cra, 
                    new SortView("Flèche magique", "Occasionne des dommages Air et vole la portée de la cible.", Resources.img_cra_sort1),
                    new SortView("Flèche de recul", "Occasionne des dommages Air aux ennemis et pousse la cible.", Resources.img_cra_sort2),
                    new SortView("Flèche de dispersion", "Pousse les ennemis et alliés, même s'ils sont bloqués par d'autres entités.", Resources.img_cra_sort3),
                    new SortView("Flèche glacée", "Occasionne des dommages Feu et retire des PA.", Resources.img_cra_sort4),
                    new SortView("Flèche enflammée", "Occasionne des dommages Feu et pousse les cibles présentes dans la zone d'effet du sort.", Resources.img_cra_sort5),
                    new SortView("Tir éloigné", "Augmente la portée des cibles présentes dans la zone d'effet.", Resources.img_cra_sort6),
                    new SortView("Flèche d’expiation", "Occasionne des dommages Eau, augmente les dommages du sort tous les 3 tours.", Resources.img_cra_sort7),
                    new SortView("Oeil de taupe", "Réduit la portée des personnages ciblés, vole de la vie dans l'élément Eau et repère les objets invisibles dans sa zone d'effet.", Resources.img_cra_sort8),
                    new SortView("Tir critique", "Augmente la probabilité de faire un coup critique.", Resources.img_cra_sort9),
                    new SortView("Flèche d’immobilisation", "Occasionne des dommages Eau et vole des PM à la cible.", Resources.img_cra_sort10),
                    new SortView("Flèche punitive", "Occasionne des dommages Terre et augmente les dommages du sort tous les 2 tours.", Resources.img_cra_sort11),
                    new SortView("Tir puissant", "Augmente les dommages des sorts.", Resources.img_cra_sort12),
                    new SortView("Flèche harcelante", "Occasionne des dommages Air sans ligne de vue.", Resources.img_cra_sort13),
                    new SortView("Flèche empisonnée", "Occasionne des dommages Neutre sur plusieurs tours et retire des PM.", Resources.img_cra_sort14),
                    new SortView("Flèche persécutrice", "Occasionne des dommages Air et Feu.", Resources.img_cra_sort15),
                    new SortView("Flèche destructrice.", "Occasionne des dommages Terre et réduit les dommages occasionnés par la cible.", Resources.img_cra_sort16),
                    new SortView("Flèche absorbante.", "Vole de la vie dans l'élément Air.", Resources.img_cra_sort17),
                    new SortView("Flèche cinglante", "Applique de l'Érosion aux ennemis et repousse de 2 cases.", Resources.img_cra_sort18),
                    new SortView("Flèche ralentissante", "Occasionne des dommages Eau et retire des PA en zone.", Resources.img_cra_sort19),
                    new SortView("Flèche explosive", "Occasionne des dommages Feu en zone.", Resources.img_cra_sort20),
                    new SortView("Maîtrise de l’arc", "Augmente les dommages.", Resources.img_cra_sort21)),

                new ClasseView(
                    "Ecaflip",
                    "Les Ecaflips sont des guerriers joueurs qui se fourrent dans les endroits où l'on peut gagner gros, et perdre beaucoup... \nUn Ecaflip bien dans sa peau parie sans arrêt, pour tout et pour rien. \nMais attention, il prend le jeu très au sérieux et ira même jusqu'à risquer sa vie sur un jet de dés pour tenter de remporter la mise...",  
                    Resources.img_classe_ecaflip, 
                    new SortView("Pile ou Face", "Occasionne des dommages Terre. Les dommages du sort sont réduits au tour suivant.", Resources.img_ecaflip_sort1),
                    new SortView("Chance d’Ecaflip", "Divise par 2 les dommages subis pendant 1 tour. Au tour suivant, les dommages reçus sont augmentés de 50%", Resources.img_ecaflip_sort2),
                    new SortView("Bond du félin", "Augmente les PM de la cible de 1 pendant 1 tour.", Resources.img_ecaflip_sort3),
                    new SortView("Bluff", "Occasionne dommages Air. En coup critique, occasionne des dommages Eau.", Resources.img_ecaflip_sort4),
                    new SortView("Perception", "La cible est soignée de 4% de sa vie par ennemi à proximité. Détecte les entités invisibles dans la zone d'effet.", Resources.img_ecaflip_sort5),
                    new SortView("Topkaj", "Occasionne des dommages Feu.", Resources.img_ecaflip_sort6),
                    new SortView("Griffe invocatrice", "Invoque un Chaton qui inflige des dégâts Eau à ses ennemis. À chaque fois qu'il attaque, le Chaton augmente la Puissance de son invocateur.", Resources.img_ecaflip_sort7),
                    new SortView("Tout ou rien", "Sur ennemis : Occasionne des dommages Eau en zone immédiatement et soigne au tour suivant. Sur alliés : Soigne en zone immédiatement et occasionne des dommages Eau au tour suivant. Le lanceur est toujours affecté en premier.", Resources.img_ecaflip_sort8),
                    new SortView("Roulette", "Invoque une Roulette qui procure un bonus aléatoire à tout le monde au début de son tour.", Resources.img_ecaflip_sort9),
                    new SortView("Contrecoup", "Applique un bouclier sur la cible. La valeur du bouclier est plus importante sur le lanceur.", Resources.img_ecaflip_sort10),
                    new SortView("Langue râpeuse", "Occasionne des dommages Feu aux ennemis. Sur ennemi : réduit la portée le tour en cours mais l'augmente le tour suivant. Sur allié : augmente la portée le tour en cours mais la réduit le tour suivant.", Resources.img_ecaflip_sort11),
                    new SortView("Roue de la fortune", "Augmente la Puissance des sorts.", Resources.img_ecaflip_sort12),
                    new SortView("Esprit félin", "Occasionne des dommages Terre et téléporte symétriquement par rapport à la cible.", Resources.img_ecaflip_sort13),
                    new SortView("Trèfle", "Applique un bonus aux Coups Critiques mais réduit les dommages d'armes pendant 2 tours. Si relancé pendant la durée de l'effet, applique un malus aux coups critiques à la place.", Resources.img_ecaflip_sort14),
                    new SortView("Odorat", "Occasionne un gain de PM mais une perte de PA en zone le tour en cours, puis un gain de PA mais une perte de PM le tour suivant. Le coût en PA du sort est remboursé pour l'Ecaflip.", Resources.img_ecaflip_sort15),
                    new SortView("Réflexes", "Occasionne des dommages Air en zone et applique un malus de vie insoignable.", Resources.img_ecaflip_sort16),
                    new SortView("Griffe joueuse", "Occasionne des dommages Terre sur plusieurs cases en ligne droite. En coup critique, occasionne des dommages Eau.", Resources.img_ecaflip_sort17),
                    new SortView("Félintion", "Vole des points de vie aux ennemis dans l'élément Eau. Pousse les ennemis et alliés.", Resources.img_ecaflip_sort18),
                    new SortView("Griffe de Ceangal", "Occasionne des dommages Air. Repousse la cible puis se rapproche d'elle.", Resources.img_ecaflip_sort19),
                    new SortView("Rekop", "Occasionne des dommages Air, Eau, Terre et Feu. Le sort est déclenché aléatoirement : dans 1, 2, ou 3 tours et les effets ne sont cumulables qu'une fois par cible. Plus les dommages sont appliqués à retardement, plus ils sont importants.", Resources.img_ecaflip_sort20),
                    new SortView("Destin d’Ecaflip", "Occasionne des dommages Terre, attire puis repousse la cible. Si la cible subit des dégâts de poussée dans le même tour, elle subit un malus de PM pendant 2 tours.", Resources.img_ecaflip_sort21)),

                new ClasseView(
                    "Eniripsa",
                    "Les Eniripsas sont des guérisseurs qui soignent d'un simple mot. \nIls utilisent le pouvoir de la parole pour soulager les souffrances de leurs alliés, mais parfois aussi pour blesser leurs ennemis. \nCertains Eniripsas sont même devenus de véritables arpenteurs du verbe, des rôdeurs des langues oubliées.",  
                    Resources.img_classe_eniripsa,
                    new SortView("Mot Blessant", "Occasionne des dommages Air. Les alliés à proximité du lanceur (2 cases ou moins) sont soignés à hauteur de 100% des dommages occasionnés.", Resources.img_eniripsa_sort1),
                    new SortView("Mot alternatif", "Occasionne des dommages Feu aux ennemis. Soigne les alliés.", Resources.img_eniripsa_sort2),
                    new SortView("Mot d’Amitié", "Invoque un Lapino qui Stimule le lanceur tant qu'il est en vie : il donne 2 PA. Le Lapino soigne ses alliés. Si lancé alors que le Lapino est présent sur le terrain, téléporte le Lapino sur la cellule ciblée. Quand le Lapino meurt, il pose un glyphe de fin de tour qui soigne les alliés, et ne peut plus être invoqué pendant 3 tours.", Resources.img_eniripsa_sort3),
                    new SortView("Mot interdit", "Occasionne des dommages Eau. Les alliés à proximité de la cible (2 cases ou moins) sont soignés à hauteur de 100% des dommages occasionnés.", Resources.img_eniripsa_sort4),
                    new SortView("Mot de Frayeur", "Pousse la cible.", Resources.img_eniripsa_sort5),
                    new SortView("Mot stimulant", "La cible devient Stimulée : elle gagne 2 PA pendant 3 tours. N'affecte pas les Eniripsas.", Resources.img_eniripsa_sort6),
                    new SortView("Mot brutal", "Occasionne des dommages Terre.", Resources.img_eniripsa_sort7),
                    new SortView("Mot de Jouvence", "Soigne un allié et lui retire 1 tour d'envoûtement.", Resources.img_eniripsa_sort8),
                    new SortView("Mot sélectif", "Occasionne des dommages Feu aux ennemis et soigne les alliés en zone.", Resources.img_eniripsa_sort9),
                    new SortView("Mot éclatant", "Occasionne des dommages Eau en zone. Les alliés à proximité des cibles (2 cases ou moins) sont soignés à hauteur de 100% des dommages occasionnés.", Resources.img_eniripsa_sort10),
                    new SortView("Mot de prévention", "La cible gagne des points de bouclier pendant 2 tours.", Resources.img_eniripsa_sort11),
                    new SortView("Mot turbulent", "Vole de la vie dans l'élément Air.", Resources.img_eniripsa_sort12),
                    new SortView("Mot d’immobilisation", "Enlève des PM pendant 1 tour. À la fin de son tour, la cible soigne les alliés à proximité (2 cases ou moins).", Resources.img_eniripsa_sort13),
                    new SortView("Mot déroutant", "Occasionne des dommages Feu aux ennemis et soigne les alliés.", Resources.img_eniripsa_sort14),
                    new SortView("Mot tournoyant", "Occasionne des dommages Air en zone. Les alliés à proximité du lanceur (2 cases ou moins) sont soignés à hauteur de 100% des dommages occasionnés.", Resources.img_eniripsa_sort15),
                    new SortView("Mot fracassant", "Occasionne des dommages Eau et retire des PA aux ennemis.", Resources.img_eniripsa_sort16),
                    new SortView("Mot de silence", "Retire des PA en zone et dévoile les entités invisibles. Les alliés Stimulés ainsi que le lanceur ne sont pas affectés.", Resources.img_eniripsa_sort17),
                    new SortView("Mot de régénération", "La cible est soignée à retardement : au début du prochain tour du lanceur, et au tour suivant.", Resources.img_eniripsa_sort18),
                    new SortView("Mot d’envol", "Échange de place avec un allié (hors invocations). Retire l'état Stimulé. Applique l'état Insoignable au lanceur si l'allié n'est pas Stimulé. Le Lapino peut être ciblé mais il est tué.", Resources.img_eniripsa_sort19),
                    new SortView("Mot revitalisant", "Tous les alliés Stimulés sont soignés, mais l'état Stimulé est retiré. Tue le Lapino s'il était invoqué. Passe l'intervalle de relance des sorts Mot Stimulant et Mot d'Abnégation à 1 tour.", Resources.img_eniripsa_sort20),
                    new SortView("Mot de reconstitution", "Soigne totalement la cible alliée mais la rend ensuite Insoignable pour 3 tours.", Resources.img_eniripsa_sort21)),

                new ClasseView(
                    "Enutrof",
                    "Les Enutrofs sont des chasseurs de trésor avides de kamas, qui malgré leur grand âge courent comme des dragodindes à la vue d'un coffre bien rempli. \nIls sont experts dans l'art de ralentir leurs ennemis : ils peuvent ainsi les harceler avant de les assommer à grands coups de pelle le moment venu ! ",  
                    Resources.img_classe_enutrof,
                    new SortView("Sac animé", "Invoque un Sac Animé qui subit les dommages à la place de ses alliés. Le Sac Animé disparaît après 4 tours. Quand il est attaqué par un allié, ce dernier est soigné.", Resources.img_enutrof_sort1),
                    new SortView("Lancer de pelle", "Occasionne des dommages Terre et retire de la Portée à la cible.", Resources.img_enutrof_sort2),
                    new SortView("Lancer de pièces", "Occasionne des dommages Eau à longue portée.", Resources.img_enutrof_sort3),
                    new SortView("Pelle fantomatique", "Réduit la durée des effets et occasionne des dommages Feu.", Resources.img_enutrof_sort4),
                    new SortView("Accélération", "Augmente les PM de la cible.", Resources.img_enutrof_sort5),
                    new SortView("Boite de pandore", "Rend des PV en fonction de la Vitalité maximale de la cible mais réduit la capacité du lanceur à retirer des PM le tour suivant.", Resources.img_enutrof_sort6),
                    new SortView("Remblai", "Occasionne des dommages Terre en croix.", Resources.img_enutrof_sort7),
                    new SortView("Clé réductrice", "Réduit la portée.", Resources.img_enutrof_sort8),
                    new SortView("Force de l’âge", "Occasionne des dommages Terre et un malus d'esquive PM à courte portée.", Resources.img_enutrof_sort9),
                    new SortView("Pelle animée", "Invoque une pelle qui repousse les ennemis et réduit leurs résistances aux pertes de PM. Quand elle est attaquée par un allié, ce dernier est soigné.", Resources.img_enutrof_sort10),
                    new SortView("Cupidité", "Augmente les dommages des alliés et des ennemis en zone.", Resources.img_enutrof_sort11),
                    new SortView("Roulage de pelle", "Occasionne des dommages Feu.", Resources.img_enutrof_sort12),
                    new SortView("Maladresse", "Retire des PM.", Resources.img_enutrof_sort13),
                    new SortView("Maladresse de masse", "Retire des PA en zone aux ennemis.", Resources.img_enutrof_sort14),
                    new SortView("Chance", "Augmente la Fuite de la cible pendant le tour en cours puis augmente sa Puissance le tour suivant.", Resources.img_enutrof_sort15),
                    new SortView("Pelle de jugement", "Occasionne des dommages Eau et retire des PM.", Resources.img_enutrof_sort16),
                    new SortView("Pelle massacrante", "Occasionne des dommages Eau.", Resources.img_enutrof_sort17),
                    new SortView("Retraite anticipée", "Interdit l'utilisation des sorts de déplacement et empêche d'utiliser des PM. Le lanceur du sort est affecté au tour suivant. Les effets ne peuvent pas être désenvoûtés.", Resources.img_enutrof_sort18),
                    new SortView("Corruption", "Sur Allié : soigne et fixe l'état Pacifiste pendant 1 tour Sur Ennemi : fixe l'état Pacifiste et Invulnérable pendant 1 tour Les effets du sort ne peuvent pas être désenvoûtés.", Resources.img_enutrof_sort19),
                    new SortView("Désinvocation", "Occasionne des dommages Feu. Les dommages sont doublés sur invocations.", Resources.img_enutrof_sort20),
                    new SortView("Coffre Animé", "Invoque un Coffre Animé qui tacle les ennemis. Il occasionne des dommages en zone autour de lui et détecte les invisibles. Moins il a de vie et plus ses dommages sont importants. Quand il est attaqué par un allié, ce dernier est soigné.", Resources.img_enutrof_sort21)),

                new ClasseView(
                    "Feca",
                    "Les Fécas sont de loyaux protecteurs toujours sur la défensive. \nIls sont appréciés dans les groupes d'aventuriers pour leurs armures élémentaires et leur capacité à encaisser les coups durs. \nIls sont également maîtres dans l'art des signes magiques : quand il va y avoir du grabuge, les Fécas sortent leurs glyphes !",  
                    Resources.img_classe_feca,
                    new SortView("Aveuglement", "Occasionne des dommages Neutre en zone et retire des PA à la cible. L'effet de retrait de PA ne peut pas être cumulé sur une même cible, ni désenvoûté.", Resources.img_feca_sort1),
                    new SortView("Attaque naturelle", "Occasionne des dommages Feu et vole de l’Intelligence.", Resources.img_feca_sort2),
                    new SortView("Rempart", "Réduit les dommages reçus. La protection sur les alliés est plus faible. Ne peut pas être lancé dans l’état Glyphor.", Resources.img_feca_sort3),
                    new SortView("Typhon", "Occasionne des dommages Air et vole de l’Agilité en zone.", Resources.img_feca_sort4),
                    new SortView("Bulle", "Occasionne des dommages Eau et diminue la portée.", Resources.img_feca_sort5),
                    new SortView("Barricade", "Réduit tous les dommages subis en mêlée pendant 1 tour et augmente les PM de la cible si elle reçoit des dommages à distance. Ne peut pas être lancé dans l’état « Glyphor ».", Resources.img_feca_sort6),
                    new SortView("Glyphe agressif", "Pose un glyphe qui occasionne des dommages Air et attire en début de tour. Les ennemis et alliés occasionnent moins de dommages tant qu’ils sont présents dans la zone d’effet du glyphe. Empêche le lancer d'autres glyphes élémentaires dans le même tour.", Resources.img_feca_sort7),
                    new SortView("Léthargie", "Occasionne des dommages Feu et retire des PM. Les pertes de PM ne peuvent être ni cumulées ni désenvoûtées.", Resources.img_feca_sort8),
                    new SortView("Attaque nuageuse", "Occasionne des dommages Eau et vole de la Chance.", Resources.img_feca_sort9),
                    new SortView("Bastion", "Réduit tous les dommages subis à distance. Augmente la Puissance de la cible si elle reçoit des dommages de mêlée. Ne peut pas être lancé dans l’état Glyphor.", Resources.img_feca_sort10),
                    new SortView("Retour du bâton", "Occasionne des dommages Terre et vole de la Force.", Resources.img_feca_sort11),
                    new SortView("Téléglyphe", "Téléporte sur la cellule ciblée et déclenche les glyphes ciblés.", Resources.img_feca_sort12),
                    new SortView("Glyphe de répulsion", "Pose un glyphe qui occasionne en fin de tour des dommages Feu, Eau, Air et Terre aux cibles autour de la cellule visée.", Resources.img_feca_sort13),
                    new SortView("Trêve", "Réduit tous les dommages subis par les alliés et les ennemis pendant 1 tour. Le lanceur ne peut pas occasionner de dommages pendant son tour suivant. Ne peut pas être lancé dans l’état Glyphor.", Resources.img_feca_sort14),
                    new SortView("Glyphe d’aveuglement", "Pose un glyphe qui occasionne des dommages Terre. Les ennemis et alliés perdent des PA tant qu’ils sont présents dans la zone d’effet du glyphe. Empêche le lancer d'autres glyphes élémentaires dans le même tour.", Resources.img_feca_sort15),
                    new SortView("Frisson", "Rapproche les cibles et occasionne aux ennemis des dommages Air en cône.", Resources.img_feca_sort16),
                    new SortView("Glyphe optique", "Pose un glyphe qui occasionne des dommages Eau. Les alliés et ennemis perdent de la Portée tant qu’ils sont présents dans la zone d’effet du glyphe. Empêche le lancer d'autres glyphes élémentaires dans le même tour.", Resources.img_feca_sort17),
                    new SortView("Mise en garde", "Augmente les dommages des Glyphes et la Puissance du lanceur. Désactive les effets des sorts de protection Feca.", Resources.img_feca_sort18),
                    new SortView("Glyphe gravitationnel", "Pose un glyphe qui applique l'état Inébranlable empêchant le lanceur d'être poussé. Applique l'état Pesanteur sur les alliés et les ennemis. Affecte les alliés et ennemis présents dans la zone d'effet.", Resources.img_feca_sort19),
                    new SortView("Glyphe enflammé", "Pose un glyphe qui occasionne des dommages Feu. Les ennemis et alliés perdent des PM tant qu’ils sont présents dans la zone d’effet du glyphe. Empêche le lancer d'autres glyphes élémentaires dans le même tour.", Resources.img_feca_sort20),
                    new SortView("Bouclier Féca", "Réduit les dommages subis. Ne peut pas être lancé dans l’état Glyphor.", Resources.img_feca_sort21)),

                new ClasseView(
                    "Iop", 
                    "Les Iops sont des guerriers fonceurs et sans reproche ! \nUne chose est sûre : les Iops savent faire parler les armes. \nD'ailleurs, se retrouver pris dans une bagarre au moins une fois par jour est pour eux un signe de bonne santé. \nLeur tempérament impétueux fait des Iops des paladins de l'extrême, capables du meilleur... comme du pire !",  
                     Resources.img_classe_iop, 
                     new SortView("Pression", "Occasionne des dommages Terre et applique un malus d'Érosion.", Resources.img_iop_sort1), 
                     new SortView("Bond", "Téléporte sur la case ciblée. Augmente les dommages reçus par les ennemis situés sur les cases adjacentes.", Resources.img_iop_sort2), 
                     new SortView("Intimidation", "Occasionne des dommages Neutre sur les ennemis et repousse la cible.", Resources.img_iop_sort3), 
                     new SortView("Déferlement", "Occasionne des dommages Eau aux ennemis et rapproche le lanceur de la cible. Le lanceur gagne des points de bouclier.", Resources.img_iop_sort4), 
                     new SortView("Epée divine", "Occasionne des dommages Air et augmente les dommages des alliés ciblés.", Resources.img_iop_sort5), 
                     new SortView("Epée destructrice", "Occasionne des dommages Feu aux ennemis et attire les cibles vers le lanceur.", Resources.img_iop_sort6),
                     new SortView("Massacre", "Lorsque la cible ennemie reçoit des dommages de sorts, elle occasionne 50% de ces dommages aux ennemis au contact.", Resources.img_iop_sort7),
                     new SortView("Souffle", "Repousse les alliés et les ennemis situés autour de la cellule ciblée.", Resources.img_iop_sort8),
                     new SortView("Concentration", "Occasionne des dommages Terre. Les dommages sont augmentés contre les Invocations. ", Resources.img_iop_sort9),
                     new SortView("Couper", "Occasionne des dommages Feu et retire des PM.", Resources.img_iop_sort10),
                     new SortView("Friction", "Attire la cible d'une case. La cible se rapproche ensuite de l'attaquant si elle reçoit des dommages issus de sorts pendant 2 tours. Nécessite d'être aligné avec la cible.", Resources.img_iop_sort11),
                     new SortView("Duel", "Retire leurs PM à la cible et au lanceur, leur applique l'état Pesanteur et les rend invulnérable aux dommages à distance. Ne fonctionne que si lancé sur un ennemi.", Resources.img_iop_sort12),
                     new SortView("Epée du jugement", "Occasionne des dommages Air et Feu sans ligne de vue.", Resources.img_iop_sort13),
                     new SortView("Puissance", "Augmente la Puissance de la cible.", Resources.img_iop_sort14),
                     new SortView("Précipitation", "Augmente les PA de la cible pour le tour en cours mais lui retire des PA le tour suivant. Interdit l'utilisation des armes et du sort Colère de Iop.", Resources.img_iop_sort15),
                     new SortView("Tempête de puissance", "Occasionne des dommages Feu.", Resources.img_iop_sort16),
                     new SortView("Epée céleste", "Occasionne des dommages Air en zone.", Resources.img_iop_sort17),
                     new SortView("Vitalité", "Augmente temporairement la Vitalité de la cible en pourcentage. Le bonus de Vitalité est divisé par 2 sur les cibles autres que le lanceur.", Resources.img_iop_sort18),
                     new SortView("Epée de Iop", "Occasionne des dommages Terre en croix.", Resources.img_iop_sort19),
                     new SortView("Epée du destin", "Occasionne des dommages Feu. Les dommages sont augmentés à partir du second lancer.", Resources.img_iop_sort20),
                     new SortView("Colère de Iop", "Occasionne des dommages Terre. Augmente les dommages du sort au troisième tour après son lancer.", Resources.img_iop_sort21)),

                new ClasseView(
                    "Osamodas",
                    "Les Osamodas sont des dompteurs nés ! \nIls ont le pouvoir d'invoquer des créatures et sont de remarquables dresseurs. \nUne rumeur prétend qu'ils taillent leurs vêtements dans la peau de leurs ennemis, mais allez donc leur demander ce qu'il en est... \nSi vous êtes de son côté, un Osamodas sera aux petits soins pour vous. \nDans le cas contraire, peut-être terminerez-vous votre vie sous la forme d'une botte ou d'un bonnet fourré.",  
                    Resources.img_classe_osamodas,
                    new SortView("Dragonique", "Occasionne des dommages Feu, les entités qui attaquent la cible sont soignées.", Resources.img_osamodas_sort1),
                    new SortView("Canine", "Occasionne des dommages Air et retire du Tacle.", Resources.img_osamodas_sort2),
                    new SortView("Tofu noir", "Invoque un Tofu noir qui retire du Tacle aux ennemis et qui gagne 50% de l'Agilité et des Dommages Air du lanceur. Si contrôlé par son invocateur, peut échanger de place avec un allié. Empêche l'invocation d'un Bouftou, d'un Crapaud ou d'un Dragonnet dans le même tour.", Resources.img_osamodas_sort3),
                    new SortView("Lien animal", "Fusionne avec une invocation alliée pour modifier sa propre apparence et prendre le contrôle des invocations de la même famille. L'invocation ciblée est tuée. \nTofu : • Tous les Tofus gagnent 2 PA. • Le lanceur gagne 2 PM. Bouftou : • Tous les Bouftous gagnent 2PA. • Le lanceur réduit les dommages subis de 20%. Dragonnet : • Tous les Dragonnets gagnent 2 PA. • Le lanceur gagne un bonus aux soins. Crapaud : • Tous les Crapauds gagnent 2 PA. • Le lanceur gagne un bonus aux dommages.", Resources.img_osamodas_sort4),
                    new SortView("Fossile", "Occasionne des dommages Terre et retire des PM.", Resources.img_osamodas_sort5),
                    new SortView("Bouftou", "Invoque un Bouftou qui tacle les ennemis, retire de la Fuite et qui gagne 50% de la Force, des Dommages Terre et des Dommages Neutre du lanceur. Si contrôlé par son invocateur, peut attirer une cible. Empêche l'invocation d'un Dragonnet, d'un Crapaud ou d'un Tofu dans le même tour.", Resources.img_osamodas_sort6),
                    new SortView("Rappel", "Tue une invocation alliée. Récupère les PA qui ont servi à l'invoquer si c'est un Tofu, Bouftou, un Crapaud ou Dragonnet.", Resources.img_osamodas_sort7),
                    new SortView("Tofu dodu", "Invoque un Tofu Dodu qui repousse les ennemis et qui gagne 50% de l'Agilité et des Dommages Air du lanceur. Si contrôlé par son invocateur, peut échanger de place avec un allié. Empêche l'invocation d'un Bouftou, d'un Crapaud ou d'un Dragonnet dans le même tour.", Resources.img_osamodas_sort8),
                    new SortView("Fouet", "Sur ennemis : occasionne des dommages dans l'élément de la Transformation du lanceur. Sur alliés : applique un effet en fonction de la transformation du lanceur : • Tofu : +2 PM • Bouftou : 20% de réduction des dommages subis • Dragonnet : Soigne la cible • Crapaud : Bonus Puissance.", Resources.img_osamodas_sort9),
                    new SortView("Plumeau", "Occasionne des dommages Air. Les dommages sont augmentés pour chaque Tofu présent sur le terrain.", Resources.img_osamodas_sort10),
                    new SortView("Bouftou noir", "Invoque un Bouftou noir qui tacle les ennemis et qui gagne 50% de la Force, des Dommages Terre et des Dommages Neutre du lanceur. Il applique l’état Pesanteur 1 tour sur 2. Si contrôlé par son invocateur, peut attirer une cible. Empêche l'invocation d'un Dragonnet, d'un Crapaud ou d'un Tofu dans le même tour.", Resources.img_osamodas_sort11),
                    new SortView("Dragonnet noir", "Invoque un Dragonnet noir qui attaque les ennemis en ligne en soignant les alliés à proximité (sauf son invocateur) et qui gagne 50% de l'Intelligence, des Dommages Feu et des Soins du lanceur. Si contrôlé par son invocateur, peut soigner un allié. Empêche l'invocation d'un Bouftou, d'un Crapaud ou d'un Tofu dans le même tour.", Resources.img_osamodas_sort12),
                    new SortView("Souffle du dragon", "Occasionne des dommages Feu. Quand un Dragonnet attaque la cible, les alliés à proximité sont soignés (sauf le lanceur).", Resources.img_osamodas_sort13),
                    new SortView("Crapaud noir", "Invoque un Crapaud Noir qui applique un poison Eau et qui gagne 50% de la Chance et des Dommages Eau du lanceur. Si contrôlé par son invocateur, peut pousser une cible jusqu'à la cellule ciblée. Empêche l'invocation d'un Bouftou, d'un Tofu ou d'un Dragonnet dans le même tour", Resources.img_osamodas_sort14),
                    new SortView("Frappe du craqueleur", "Occasionne des dommages Terre en zone.", Resources.img_osamodas_sort15),
                    new SortView("Geyser", "Occasionne des dommages Eau. Augmente la Puissance.", Resources.img_osamodas_sort16),
                    new SortView("Crapaud baveux", "Invoque un Crapaud Baveux qui occasionne des dommages Eau en zone et qui gagne 50% de la Chance et des Dommages Eau du lanceur. Si contrôlé par son invocateur, peut pousser une cible jusqu'à la cellule ciblée. Empêche l'invocation d'un Bouftou, d'un Tofu ou d'un Dragonnet dans le même tour.", Resources.img_osamodas_sort17),
                    new SortView("Laisse spirituelle", "Ressuscite le dernier personnage allié mort. Si l'invocateur meurt, le personnage ressuscité meurt également. Tant que l'allié ressuscité est en vie, les autres alliés subissent un malus de 30% de résistance dans tous les éléments.", Resources.img_osamodas_sort18),
                    new SortView("Dragonnet rouge", "Invoque un Dragonnet rouge qui désenvoûte les ennemis et qui gagne 50% de l'Intelligence, des Dommages Feu et des Soins du lanceur. Si contrôlé par son invocateur, peut soigner un allié. Empêche l'invocation d'un Bouftou, d'un Crapaud ou d'un Tofu dans le même tour.", Resources.img_osamodas_sort19),
                    new SortView("Piqûre motivante", "Augmente considérablement la Vitalité, les Dommages, les PM et les PA d’une invocation du lanceur.", Resources.img_osamodas_sort20),
                    new SortView("Symbiose", "Prend le contrôle d'une invocation alliée. Tofu : débloque un sort qui permet d'échanger de place avec un allié. Bouftou : débloque un sort qui permet d'attirer une entité. Dragonnet : débloque un sort qui permet de soigner un allié. Crapaud : débloque un sort qui repousse la cible jusqu'à la cellule ciblée.", Resources.img_osamodas_sort21)),

                new ClasseView(
                    "Pandawa",
                    "Les Pandawas sont des guerriers adeptes des arts martiaux qui savent faire des folies de leur corps ! \nIls peuvent même en faire avec le corps des autres... \nLe Pandawa sait comment soulever les foules, il porte ses alliés sur ses épaules pour mieux les protéger. \nQuant à ses ennemis, il les enverra valser dans le décor, avant de fêter sa victoire avec une bonne rasade de lait de bambou !",  
                    Resources.img_classe_pandawa,
                    new SortView("Poing enflammé", "Occasionne des dommages Feu. L'état Saoul est nécessaire.", Resources.img_pandawa_sort1),
                    new SortView("Ribote", "Occasionne des dommages Terre.", Resources.img_pandawa_sort2),
                    new SortView("Bombance", "Applique l'état Saoul et donne du tacle. Ne bloque pas le lancer des sorts Sobre.", Resources.img_pandawa_sort3),
                    new SortView("Epouvante", "Repousse la cible et réduit la probabilité d'occasionner des critiques aux ennemis.", Resources.img_pandawa_sort4),
                    new SortView("Souffle alcoolisé", "Occasionne des dommages Air et pousse la cible. L'état Saoul est nécessaire.", Resources.img_pandawa_sort5),
                    new SortView("Karcham", "Porte la cible. Au second lancer, jette la cible à 6 cellules maximum. Désactive les lignes de vue des sorts de la cible portée.", Resources.img_pandawa_sort6),
                    new SortView("Schnaps", "Occasionne des dommages Air en zone.", Resources.img_pandawa_sort7),
                    new SortView("Propulsion", "Lance l'entité portée. Occasionne des dommages Feu aux ennemis et repousse autour de la cellule ciblée.", Resources.img_pandawa_sort8),
                    new SortView("Ivresse", "Invoque un tonneau qui attire les ennemis. Il attire également les alliés s'ils sont dans l'état Saoul. S'il est porté ou jeté : soigne autour de lui.", Resources.img_pandawa_sort9),
                    new SortView("Stabilisation", "Empêche la cible d'être déplacée. Augmente les résistances aux pertes de PM.", Resources.img_pandawa_sort10),
                    new SortView("Eviction", "Occasionne des dommages Terre aux ennemis. La cible est téléportée derrière le lanceur.", Resources.img_pandawa_sort11),
                    new SortView("Ethylo", "Occasionne des dommages Eau. Applique un malus au retrait de PA.", Resources.img_pandawa_sort12),
                    new SortView("Souillure", "Réduit la durée des effets sur la cible de 1 tour. Applique un malus de Puissance. L'état Saoul est nécessaire.", Resources.img_pandawa_sort13),
                    new SortView("Vulnérabilité", "Augmente les dommages reçus par la cible pendant 2 tours. L'état Saoul est nécessaire.", Resources.img_pandawa_sort14),
                    new SortView("Vague à lame", "Occasionne des dommages Eau.", Resources.img_pandawa_sort15),
                    new SortView("Colère de Zatoïshwan", "Applique l'état Saoul. Augmente les dommages et les PA du lanceur.", Resources.img_pandawa_sort16),
                    new SortView("Flasque explosive", "Occasionne des dommages Feu en zone.", Resources.img_pandawa_sort17),
                    new SortView("Vertige", "Lance l'entité portée et augmente son tacle. Attire les entités alignées avec la cellule ciblée.", Resources.img_pandawa_sort18),
                    new SortView("Pandatak", "Occasionne des dommages Terre sur plusieurs cases en ligne.", Resources.img_pandawa_sort19),
                    new SortView("Pandanlku", "Augmente les PM de la cible. Nécessite l'état Saoul.", Resources.img_pandawa_sort20),
                    new SortView("Lien Spiritueux", "Invoque un Pandawasta qui bloque les déplacements des adversaires. Nécessite l'état Saoul.", Resources.img_pandawa_sort21)),

                new ClasseView(
                    "Sacrieur",
                    "Les Sacrieurs sont des berserkers qui décuplent leurs forces dès qu'ils sont frappés ! \nN'ayant pas peur de recevoir des coups, ni de s'exposer aux blessures, ils seront souvent en première ligne, prêts à verser le premier sang ! \nLe Sacrieur est vraiment le compagnon idéal pour vos longues soirées guerrières...",  
                    Resources.img_classe_sacrieur,
                    new SortView("Furie", "Occasionne des dommages Air. Les dommages sont augmentés en fonction du nombre de charges de Souffrance. Applique 1 charge de Souffrance : plus le Sacrieur a de charges de Souffrance, plus il occasionne de dommages. À partir de 3 charges de Souffrance, le Sacrieur change d'apparence et gagne un bonus supplémentaire de dommages.", Resources.img_sacrieur_sort1),
                    new SortView("Absorption", "Vole de la vie dans l'élément Terre. Retire 1 charge de Souffrance. Moins le Sacrieur a de charges de Souffrance, plus il a de Vitalité. À partir de 3 charges de Souffrance négatives, le Sacrieur change d'apparence et gagne un bonus de réduction de dommages.", Resources.img_sacrieur_sort2),
                    new SortView("Attirance", "Attire la cible.", Resources.img_sacrieur_sort3),
                    new SortView("Stase", "Occasionne des dommages Eau et retire des PM. Retire 1 charge de Souffrance.", Resources.img_sacrieur_sort4),
                    new SortView("Douleur motivante", "Occasionne des dommages Feu en zone. Les dommages sont augmentés en fonction du nombre de charges de Souffrance. Applique 1 charge de Souffrance.", Resources.img_sacrieur_sort5),
                    new SortView("Epée volante", "Invoque une épée qui soigne le lanceur lorsqu'elle occasionne des dommages.", Resources.img_sacrieur_sort6),
                    new SortView("Assaut", "Occasionne des dommages Terre sur ennemis. Échange de position avec la cible.", Resources.img_sacrieur_sort7),
                    new SortView("Mutilation", "Augmente la Puissance et ajoute 1 charge de Souffrance.", Resources.img_sacrieur_sort8),
                    new SortView("Transposition", "Échange de position avec la cible.", Resources.img_sacrieur_sort9),
                    new SortView("Fulgurance", "Téléporte en ligne sur la première cellule disponible et occasionne des dommages Air sur les cellules traversées.", Resources.img_sacrieur_sort10),
                    new SortView("Nervosité", "Occasionne des dommages Eau. Les dommages sont augmentés en fonction du nombre de charges de Souffrance. Ajoute 1 charge de Souffrance.", Resources.img_sacrieur_sort11),
                    new SortView("Sacrifice", "Cible des alliés en zone pour recevoir les dommages à leur place. Retire 2 charges de Souffrance.", Resources.img_sacrieur_sort12),
                    new SortView("Projection", "Occasionne des dommages Eau. Le lanceur est téléporté derrière la cible.", Resources.img_sacrieur_sort13),
                    new SortView("Berserk", "Pendant 1 tour, quand le lanceur subit des dommages, il gagne de la puissance. La quantité maximale de puissance engrangée dépend du niveau de Souffrance du lanceur à la fin de son tour. Ne fonctionne pas si le lanceur est en Souffrance négative. Ajoute 2 charges de Souffrance.", Resources.img_sacrieur_sort14),
                    new SortView("Transfert de vie", "Transfère une partie des PV du lanceur vers les alliés présents dans la zone d’effet. Retire 1 charge de Souffrance.", Resources.img_sacrieur_sort15),
                    new SortView("Punition", "Occasionne des dommages Neutre. Plus les PV du lanceur sont proches de la moitié du total de ses PV, plus les dommages occasionnés sont importants.", Resources.img_sacrieur_sort16),
                    new SortView("Supplice", "Vole de la vie dans l'élément Air. Réduit les dommages de 15%. Retire 1 charge de Souffrance.", Resources.img_sacrieur_sort17),
                    new SortView("Afflux", "Occasionne des dommages Feu. Attire les cibles.", Resources.img_sacrieur_sort18),
                    new SortView("Convalescence", "Réinitialise la Souffrance. Elle ne peut pas évoluer pendant 1 tour. Le lanceur gagne 4% de dommages par niveau de Souffrance négative pendant 1 tour. Il réduit les dommages reçus de 4% par niveau de Souffrance positive pendant 1 tour.", Resources.img_sacrieur_sort19),
                    new SortView("Décimation", "Occasionne des dommages Terre. Les dommages sont augmentés en fonction du nombre de charges de Souffrance. Ajoute 1 charge de Souffrance.", Resources.img_sacrieur_sort20),
                    new SortView("Bain de sang", "Occasionne des dommages Feu en zone. Retire 1 charge de Souffrance par ennemi présent dans la zone.", Resources.img_sacrieur_sort21)),

                new ClasseView(
                    "Sadida",
                    "Les Sadidas sont des invocateurs qui empoisonnent la vie de leurs ennemis ! \nApprivoiser les ronces pour en faire des armes terrifiantes, confectionner des poupées de guerre et de soins, voilà qui satisfait tout disciple Sadida digne de ce nom.",  
                    Resources.img_classe_sadida,
                    new SortView("Ronce", "Occasionne des dommages Terre. Sur un Arbre Feuillu : permet à une Bloqueuse d'échanger sa place avec l'Arbre. Elle ne peut alors plus recevoir de dommages pendant 1 tour. Sur un ennemi dans l'état Infecté : occasionne des dommages Terre à tous les ennemis dans l'état Infecté.", Resources.img_sadida_sort1),
                    new SortView("Arbre", "Plante un Arbre. Après 1 tour, l'Arbre devient Feuillu et peut être utilisé comme intermédiaire pour lancer des sorts Sadida (mais ne peut plus être poussé ou attiré).", Resources.img_sadida_sort2),
                    new SortView("Bloqueuse", "Invoque une Bloqueuse qui cherchera à aller au contact des adversaires pour les gêner.", Resources.img_sadida_sort3),
                    new SortView("Poison paralysant", "Occasionne des dommages Feu en fin de tour et applique l'état Infecté sur les ennemis. Si un ennemi dans l'état Infecté est touché par un sort monocible du Sadida : toutes les cibles qui sont dans l'état Infecté sont également affectées par ce sort. Les dommages occasionnés aux cibles secondaires infectées peuvent être déclenchés 3 fois par tour.", Resources.img_sadida_sort4),
                    new SortView("Larme", "Occasionne des dommages Eau. Sur un Arbre allié qui vient d'apparaître : le transforme en Arbre Feuillu et le rend exploitable avec les autres sorts du Sadida. Si la cible est dans l'état Infecté : occasionne des dommages Eau à tous les ennemis dans l'état Infecté.", Resources.img_sadida_sort5),
                    new SortView("Folle", "Invoque une Folle qui retire des PA et applique l'état Infecté. Si une cible dans l'état Infecté est touchée par un sort monocible du Sadida : toutes les cibles qui sont dans l'état Infecté sont affectées par ce sort. Les dommages occasionnés aux cibles secondaires infectées peuvent être déclenchés 3 fois par tour.", Resources.img_sadida_sort6),
                    new SortView("Ronce apaisante", "Occasionne une perte de PM pendant 2 tours aux ennemis. Soigne les alliés. Sur un ennemi dans l'état Infecté : occasionne une perte de PM à tous les ennemis dans l'état Infecté.", Resources.img_sadida_sort7),
                    new SortView("Puissance sylvestre", "Remplace l'Arbre Feuillu ciblé par un Arbre contrôlable qui peut : • Pousser une cible • Réduire la durée des envoûtements • Soigner en zone (3 cases autour de lui) À la fin de son tour, il redevient un Arbre.", Resources.img_sadida_sort8),
                    new SortView("Sacrifiée", "Invoque une Sacrifiée qui meurt en occasionnant des dommages Air et en appliquant l'état Infecté. Pour chaque tour où la Sacrifiée reste en vie, sa Vitalité et les dommages qu'elle occasionne augmentent.", Resources.img_sadida_sort9),
                    new SortView("Tremblement", "Dans une zone de 3 cases autour de chaque Arbre Feuillu : • Occasionne des dommages Feu • Attire les cibles • Détecte les invisibles.", Resources.img_sadida_sort10),
                    new SortView("Don naturel", "Les alliés (hors invocations) situés à 2 cases ou moins de l'Arbre Feuillu ciblé sont soignés et partagent les dommages reçus entre eux pendant 1 tour. L'Arbre Feuillu ciblé est tué.", Resources.img_sadida_sort11),
                    new SortView("Ronces multiples", "Occasionne des dommages Terre en zone. N'affecte pas les invocations du lanceur.", Resources.img_sadida_sort12),
                    new SortView("Sacrifice poupesque", "Occasionne des dommages Eau aux ennemis. Vole de la vie dans l'élément Eau aux alliés et aux invocations. Sur un ennemi dans l'état Infecté : occasionne des dommages Eau à tous les ennemis dans l'état Infecté.", Resources.img_sadida_sort13),
                    new SortView("Vent empoisonné", "Tue une poupée du lanceur pour la transformer en Arbre.", Resources.img_sadida_sort14),
                    new SortView("Gonflable", "Invoque une Gonflable qui soigne (jusqu'à 3 cases autour d'elle) et donne des PM aux alliés. Elle soigne également tous les alliés au contact des Arbres Feuillus.", Resources.img_sadida_sort15),
                    new SortView("Ronces agressives", "Occasionne des dommages Terre et donne 1PM au lanceur. Sur un ennemi dans l'état Infecté : exécute le sort sur tous les ennemis dans l'état Infecté.", Resources.img_sadida_sort16),
                    new SortView("Herbe folle", "Occasionne des dommages Feu et retire des PM en zone.", Resources.img_sadida_sort17),
                    new SortView("Arbre de vie", "Transforme l'Arbre Feuillu ciblé en Arbre de vie. Pendant 2 tours, chaque dommage reçu par l'Arbre de vie est rendu à son attaquant sous forme de soin. Soigne les invocations Sadida à chaque tour de jeu. Après 2 tours, l'Arbre de vie redevient un Arbre Feuillu.", Resources.img_sadida_sort18),
                    new SortView("Feu de brousse", "Occasionne des dommages Feu et Eau. Sur un ennemi dans l'état Infecté : occasionne des dommages Feu et Eau à tous les ennemis dans l'état Infecté.", Resources.img_sadida_sort19),
                    new SortView("Ronce insolente", "Réduit de 4 tours la durée des envoûtements de la cible. Sur un ennemi dans l'état Infecté : réduit la durée des envoûtements de tous les ennemis dans l'état Infecté.", Resources.img_sadida_sort20),
                    new SortView("Suipuissante", "Invoque une Surpuissante qui retire des PM et de l'esquive PM aux ennemis en zone, ainsi qu'aux ennemis au contact des Arbres Feuillus.", Resources.img_sadida_sort21)),

                new ClasseView(
                    "Sram",
                    "Les Srams sont des assassins qui aiment les bourses, rebondies de préférence. \nTrousser les pans d'une tunique, tâter le fond d'une poche, faire preuve de doigté, palper enfin des bijoux tant convoités avant de poser un piège ou d'asséner un coup mortel, voilà la vie d'un disciple de Sram !",  
                    Resources.img_classe_sram,
                    new SortView("Sournoiserie", "Occasionne des dommages Terre.", Resources.img_sram_sort1),
                    new SortView("Piège sournois", "Occasionne des dommages Feu et attire.", Resources.img_sram_sort2),
                    new SortView("Invisibilité", "Rend invisible.", Resources.img_sram_sort3),
                    new SortView("Poison insidieux", "Empoisonne la cible pendant 2 tours en occasionnant des dommages Air.", Resources.img_sram_sort4),
                    new SortView("Fourvoiement", "Occasionne des dommages Air et Terre. Vole de l'Agilité et de la Force. Applique de l'érosion.", Resources.img_sram_sort5),
                    new SortView("Coup sournois", "Occasionne des dommages Feu sur les ennemis. Pousse la cible.", Resources.img_sram_sort6),
                    new SortView("Double", "Invoque un double contrôlable qui possède les mêmes caractéristiques que l'invocateur. N'attaque pas et meurt au bout de 2 tours en échangeant de place avec son invocateur.", Resources.img_sram_sort7),
                    new SortView("Piège fangeux", "Pose un piège qui occasionne des dommages Eau. Les alliés à proximité de la cible sont soignés à hauteur de 50% des dommages occasionnés.", Resources.img_sram_sort8),
                    new SortView("Piège de masse", "Pose un piège mono-cellule qui occasionne des dommages Terre en zone.", Resources.img_sram_sort9),
                    new SortView("Cruauté", "Occasionne des dommages Eau et augmente les PM du lanceur.", Resources.img_sram_sort10),
                    new SortView("Piège empoisonné", "Empoisonne la cible en occasionnant des dommages Air pendant 3 tours.", Resources.img_sram_sort11),
                    new SortView("Concentration de chakra", "Vole de la vie dans l'élément Feu lorsque la cible déclenche un piège.", Resources.img_sram_sort12),
                    new SortView("Piège d’immobilisation", "Retire des PM.", Resources.img_sram_sort13),
                    new SortView("Piège insidieux", "Pose un piège. Une fois déclenché, les ennemis qui terminent leur tour dans sa zone d'effet subissent des dommages Air.", Resources.img_sram_sort14),
                    new SortView("Piège répulsif", "Repousse les alliés et les ennemis. Occasionne des dommages Air aux ennemis.", Resources.img_sram_sort15),
                    new SortView("Peur", "Pousse un allié ou un ennemi sur la cellule ciblée.", Resources.img_sram_sort16),
                    new SortView("Arnaque", "Occasionne des dommages Air.", Resources.img_sram_sort17),
                    new SortView("Poisse", "Vole de la vie dans l'élément Eau et réduit les chances de Coup critique.", Resources.img_sram_sort18),
                    new SortView("Fourberie", "Occasionne des dommages Feu en zone. Attire les cibles. Vole de l'Intelligence.", Resources.img_sram_sort19),
                    new SortView("Attaque mortelle", "Occasionne des dommages Terre.", Resources.img_sram_sort20),
                    new SortView("Piège mortel", "Occasionne des dommages Terre.", Resources.img_sram_sort21)),

                new ClasseView(
                    "Xelor",
                    "Les Xélors sont des mages qui maîtrisent le temps et toutes les mécaniques qui donnent l'heure : carillons, horloges et pendules leur obéissent au doigt et à l'œil. \nLes Xélors jouent donc avec le temps pour ralentir un ennemi ou se téléporter où bon leur semble.",  
                    Resources.img_classe_xelor,
                    new SortView("Ralentissement", "Occasionne des dommages Eau et retire 1 PA à la cible. Retire 1 PA supplémentaire aux ennemis dans l'état Téléfrag. Le retrait de PA ne peut pas être désenvoûté.", Resources.img_xelor_sort1),
                    new SortView("Aiguille", "Occasionne des dommages Feu et retire 1 PA à la cible. Retire des PA supplémentaires aux ennemis dans l'état Téléfrag. Le retrait de PA ne peut pas être désenvoûté. Retire l'état Téléfrag.", Resources.img_xelor_sort2),
                    new SortView("Téléportation", "Téléporte le lanceur symétriquement par rapport à la cible. Le lanceur gagne 2 PA pour 1 tour à chaque fois qu’il génère un Téléfrag. Le temps de relance est supprimé quand un Téléfrag est généré ou consommé. Un Téléfrag est généré lorsqu'une entité prend la place d'une autre.", Resources.img_xelor_sort3),
                    new SortView("Flétrissement", "Occasionne des dommages Air en ligne. Occasionne des dommages supplémentaires aux ennemis dans l'état Téléfrag.", Resources.img_xelor_sort4),
                    new SortView("Rembobinage", "À la fin de son tour, téléporte l'allié ciblé sur sa position de début de tour.", Resources.img_xelor_sort5),
                    new SortView("Frappe du Xélor", "Occasionne des dommages Terre aux ennemis. Téléporte la cible symétriquement par rapport au lanceur du sort.", Resources.img_xelor_sort6),
                    new SortView("Complice", "Invoque un Complice statique qui ne possède aucun sort. Il est tué si un autre Complice est invoqué.", Resources.img_xelor_sort7),
                    new SortView("Gelure", "Occasionne des dommages Air aux ennemis. Téléporte la cible à sa position précédente.", Resources.img_xelor_sort8),
                    new SortView("Sablier de Xélor", "Occasionne des dommages Feu et retire des PA à la cible en ligne et sans ligne de vue. Si la cible est dans l'état Téléfrag, l'effet du sort se joue en zone. Le retrait de PA ne peut pas être désenvoûté.", Resources.img_xelor_sort9),
                    new SortView("Vol du temps", "Occasionne des dommages Eau à la cible. Le lanceur gagne 1 PA au début de son prochain tour.", Resources.img_xelor_sort10),
                    new SortView("Flou", "Retire des PA en zone le tour en cours. Augmente les PA en zone le tour suivant.", Resources.img_xelor_sort11),
                    new SortView("Poussière temporelle", "Occasionne des dommages Feu. Les entités dans l'état Téléfrag dans la zone d'effet subissent également des dommages Feu et sont téléportées symétriquement par rapport à la cellule ciblée.", Resources.img_xelor_sort12),
                    new SortView("Raulebaque", "Replace tous les personnages à leurs positions précédentes.", Resources.img_xelor_sort13),
                    new SortView("Démotivation", "Occasionne des dommages Terre aux ennemis en diagonale. Réduit la durée des effets sur les cibles dans l'état Téléfrag et retire l'état.", Resources.img_xelor_sort14),
                    new SortView("Paradoxe temporel", "Téléporte symétriquement par rapport au Complice (ou au Cadran) les alliés et ennemis (dans une zone de 4 cases autour du Cadran). Au début du tour du Complice (ou du Cadran) : téléporte à nouveau symétriquement les mêmes cibles. Fixe le temps de relance de Cadran de Xélor et de Complice à 1.", Resources.img_xelor_sort15),
                    new SortView("Synchro", "Invoque Synchro qui gagne en puissance et se soigne quand un Téléfrag est généré, 1 fois par tour. La Synchro meurt en occasionnant des dommages Air en zone de 3 cases si elle subit un Téléfrag. Elle n'est pas affectée par les effets de Rembobinage. À partir du tour suivant son lancer, son invocateur perd 1 PA.", Resources.img_xelor_sort16),
                    new SortView("Contre", "Renvoie une partie des dommages subis en mêlée à l'attaquant.", Resources.img_xelor_sort17),
                    new SortView("Fuite", "Téléporte la cible sur sa position précédente au début du prochain tour du lanceur.", Resources.img_xelor_sort18),
                    new SortView("Horloge", "Vole de vie dans l'élément Eau. Le lanceur gagne 1 PA au début de son prochain tour. Retire des PA aux ennemis dans l'état Téléfrag et leur retire l'état. Le retrait de PA ne peut pas être désenvoûté.", Resources.img_xelor_sort19),
                    new SortView("Rayon obscur", "Occasionne des dommages Terre en ligne. Les dommages de base du sort sont doublés contre les ennemis dans l'état Téléfrag. Retire l'état Téléfrag.", Resources.img_xelor_sort20),
                    new SortView("Momification", "Gagne 2 PM et fixe l'état Téléfrag à tous les alliés et ennemis.", Resources.img_xelor_sort21))
            };
        }
    }
}
